### ISSUE TITLE
New patient and Repeate Patient Identification must done during time of Ticketing

### ISSUE THREAD

**Issue by RHCF-Parnab** [kolkata-foundation/kf-medical#11]

**Comment by banerjed** [comment]
The current software allows capturing repeat patients during each patient visit. This is a property of the patient-visit, and not the patient registration. The center needs to identify whether each patient exists or not and capture this information.

There are many separate concepts here though:
-- is the patient a repeat patient for the same medical condition (that did not get cured the first time)?
-- is the patient coming back because they have a chronic condition (diabetes, arthritis, etc)

This has to be handled in the context of the operations of a medical center and is outside the purview of this software
